[theme]
primaryColor = "#4CAF50"  # A pleasant green for accents
backgroundColor = "#FFFFFF"  # Clean white background
secondaryBackgroundColor = "#F0F2F6"  # Light grey for sidebar and widgets
textColor = "#333333"  # Dark grey for text
font = "sans serif"
